# Generated by Django 2.2.4 on 2020-04-04 18:34

from django.db import migrations


def set_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    comparison_year = 2015
    for flat in Flat.objects.all() :
        flat.new_building = flat.construction_year >= comparison_year
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_field_new_building),
    ]

