# Generated by Django 2.2.4 on 2020-05-04 10:41


from django.db import migrations
import phonenumbers

def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    Owner = apps.get_model('property', 'Owner')
    for flat in flats:
        (owner, created) = Owner.objects.get_or_create(
            full_name=flat.owner,
            owner_phone_pure=flat.owner_phone_pure,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber,
            }
        )
        owner.flats.set([flat])

def create_owners_back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200504_1439'),
    ]

    operations = [
        migrations.RunPython(create_owners, create_owners_back),
    ]
